# Generated by Django 4.1.2 on 2023-02-14 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_rename_clientes_cliente_rename_empleados_empleado_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={},
        ),
        migrations.AlterModelOptions(
            name='empleado',
            options={},
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='apellido',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='gmail',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='apellido',
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='gmail',
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='nombre',
        ),
    ]
