# Generated by Django 4.1.2 on 2023-02-14 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_cliente_options_alter_empleado_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'ordering': ['id_clientes'], 'permissions': (('Permisos_Clientes', 'delete profile'),)},
        ),
        migrations.AlterModelOptions(
            name='empleado',
            options={'ordering': ['id_empleados'], 'permissions': (('Permisos_Empleados', 'delete inmueble'),)},
        ),
    ]
