# Generated by Django 4.1.2 on 2023-02-14 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_alter_empleado_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'ordering': ['id_clientes']},
        ),
        migrations.AlterModelOptions(
            name='empleado',
            options={'ordering': ['id_empleados'], 'permissions': (('permiso1', 'edit inmueble'), ('permiso 2', 'create inmueble'), ('permiso 3', 'delete inmueble'))},
        ),
    ]
