# Generated by Django 4.1.2 on 2023-02-14 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_alter_cliente_options_alter_empleado_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inmueble',
            options={'ordering': ['ubicacion', 'precio', 'm2', 'hipoteca']},
        ),
        migrations.AddField(
            model_name='inmueble',
            name='foto',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='telefono',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='m2',
            field=models.IntegerField(),
        ),
    ]
