# Generated by Django 4.1.2 on 2023-02-15 09:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0008_alter_inmueble_options_inmueble_foto_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Foto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_inmueble', models.IntegerField()),
                ('foto', models.CharField(max_length=500, null=True)),
            ],
            options={
                'ordering': ['id_inmueble'],
            },
        ),
        migrations.AlterModelOptions(
            name='cliente',
            options={'ordering': ['id_user']},
        ),
        migrations.AlterModelOptions(
            name='empleado',
            options={'ordering': ['id_user'], 'permissions': (('permiso1', 'edit inmueble'), ('permiso 2', 'create inmueble'), ('permiso 3', 'delete inmueble'))},
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='id_clientes',
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='id_empleados',
        ),
        migrations.RemoveField(
            model_name='inmueble',
            name='foto',
        ),
        migrations.AddField(
            model_name='cliente',
            name='id_user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='empleado',
            name='id_user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
