# Generated by Django 4.1.2 on 2023-02-15 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_alter_inmueble_ubicacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inmueble',
            name='hipoteca',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
