# Generated by Django 4.1.2 on 2023-02-16 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_alter_inmueble_hipoteca'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inmueble',
            name='descripcion',
            field=models.TextField(max_length=500),
        ),
    ]
