# Generated by Django 4.1.2 on 2023-02-20 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_foto_subir_foto_a_foto_subir_foto_c'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foto',
            name='subir_foto_a',
            field=models.ImageField(null=True, upload_to='fotos_alquilar'),
        ),
        migrations.AlterField(
            model_name='foto',
            name='subir_foto_c',
            field=models.ImageField(null=True, upload_to='fotos_compra'),
        ),
    ]
