# Generated by Django 4.1.2 on 2023-02-20 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_alter_foto_subir_foto_a_alter_foto_subir_foto_c'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foto',
            name='foto',
        ),
    ]
