# Generated by Django 4.1.2 on 2023-02-20 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0017_remove_foto_foto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empleado',
            options={'ordering': ['id_user'], 'permissions': (('edit_inmueble', 'edit inmueble'), ('create_inmueble', 'create inmueble'), ('delete_inmueble', 'delete inmueble'))},
        ),
    ]
