# Generated by Django 4.1.2 on 2023-02-20 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0018_alter_empleado_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empleado',
            options={'ordering': ['id_user'], 'permissions': (('edit_inmueble', 'edit_inmueble'), ('create_inmueble', 'create_inmueble'), ('delete_inmueble', 'delete_inmueble'))},
        ),
    ]
