# Generated by Django 4.1.2 on 2023-02-21 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0020_alter_empleado_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='inmueble',
            name='ubicacion_maps',
            field=models.CharField(max_length=5000, null=True),
        ),
    ]
