# Generated by Django 4.1.2 on 2023-02-22 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0024_alter_foto_id_inmueble'),
    ]

    operations = [
        migrations.AddField(
            model_name='inmueble',
            name='ubicacion_maps',
            field=models.CharField(max_length=5000, null=True),
        ),
    ]
